services:
  php:
    image: php:8.2-fpm
    container_name: lab3_php
    volumes:
      - ./www:/var/www/html
    expose:
      - "9000"

  web:
    image: nginx:alpine
    container_name: lab3_nginx
    ports:
      - "8080:80"
    volumes:
      - ./www:/var/www/html    
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
